port: 80

docker:
  pullPolicy: IfNotPresent

image:
  cache_builder: bonnefoa/kubectl-fzf:1.0.7
  rsyncd: eeacms/rsync:2.1


resources:
  rsyncd:
    memory: 128M
    cpu: 0.2

  cache_builder:
    memory: 2G
    cpu: 1
